// Code generated by MockGen. DO NOT EDIT.
// Source: img.go
//
// Generated by this command:
//
//      mockgen --source=img.go IContext
//

// Package mock_api is a generated GoMock package.
package mock_api

import (
	image "image"
	reflect "reflect"

	gg "github.com/fogleman/gg"
	gomock "go.uber.org/mock/gomock"
	font "golang.org/x/image/font"
)

// MockIContext is a mock of IContext interface.
type MockIContext struct {
	ctrl     *gomock.Controller
	recorder *MockIContextMockRecorder
	isgomock struct{}
}

// MockIContextMockRecorder is the mock recorder for MockIContext.
type MockIContextMockRecorder struct {
	mock *MockIContext
}

// NewMockIContext creates a new mock instance.
func NewMockIContext(ctrl *gomock.Controller) *MockIContext {
	mock := &MockIContext{ctrl: ctrl}
	mock.recorder = &MockIContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContext) EXPECT() *MockIContextMockRecorder {
	return m.recorder
}

// DrawStringWrapped mocks base method.
func (m *MockIContext) DrawStringWrapped(s string, x, y, ax, ay, width, lineSpacing float64, align gg.Align) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DrawStringWrapped", s, x, y, ax, ay, width, lineSpacing, align)
}

// DrawStringWrapped indicates an expected call of DrawStringWrapped.
func (mr *MockIContextMockRecorder) DrawStringWrapped(s, x, y, ax, ay, width, lineSpacing, align any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrawStringWrapped", reflect.TypeOf((*MockIContext)(nil).DrawStringWrapped), s, x, y, ax, ay, width, lineSpacing, align)
}

// Height mocks base method.
func (m *MockIContext) Height() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Height")
	ret0, _ := ret[0].(int)
	return ret0
}

// Height indicates an expected call of Height.
func (mr *MockIContextMockRecorder) Height() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Height", reflect.TypeOf((*MockIContext)(nil).Height))
}

// Image mocks base method.
func (m *MockIContext) Image() image.Image {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Image")
	ret0, _ := ret[0].(image.Image)
	return ret0
}

// Image indicates an expected call of Image.
func (mr *MockIContextMockRecorder) Image() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Image", reflect.TypeOf((*MockIContext)(nil).Image))
}

// MeasureMultilineString mocks base method.
func (m *MockIContext) MeasureMultilineString(text string, fontSize float64) (float64, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasureMultilineString", text, fontSize)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// MeasureMultilineString indicates an expected call of MeasureMultilineString.
func (mr *MockIContextMockRecorder) MeasureMultilineString(text, lineSpacing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasureMultilineString", reflect.TypeOf((*MockIContext)(nil).MeasureMultilineString), text, lineSpacing)
}

// SetFontFace mocks base method.
func (m *MockIContext) SetFontFace(arg0 font.Face) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFontFace", arg0)
}

// SetFontFace indicates an expected call of SetFontFace.
func (mr *MockIContextMockRecorder) SetFontFace(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFontFace", reflect.TypeOf((*MockIContext)(nil).SetFontFace), arg0)
}

// SetHexColor mocks base method.
func (m *MockIContext) SetHexColor(color string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHexColor", color)
}

// SetHexColor indicates an expected call of SetHexColor.
func (mr *MockIContextMockRecorder) SetHexColor(color any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHexColor", reflect.TypeOf((*MockIContext)(nil).SetHexColor), color)
}

// SetRGB mocks base method.
func (m *MockIContext) SetRGB(r, g, b float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRGB", r, g, b)
}

// SetRGB indicates an expected call of SetRGB.
func (mr *MockIContextMockRecorder) SetRGB(r, g, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRGB", reflect.TypeOf((*MockIContext)(nil).SetRGB), r, g, b)
}

// Width mocks base method.
func (m *MockIContext) Width() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Width")
	ret0, _ := ret[0].(int)
	return ret0
}

// Width indicates an expected call of Width.
func (mr *MockIContextMockRecorder) Width() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Width", reflect.TypeOf((*MockIContext)(nil).Width))
}

// WordWrap mocks base method.
func (m *MockIContext) WordWrap(text string, width float64) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WordWrap", text, width)
	ret0, _ := ret[0].([]string)
	return ret0
}

// WordWrap indicates an expected call of WordWrap.
func (mr *MockIContextMockRecorder) WordWrap(text, width any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WordWrap", reflect.TypeOf((*MockIContext)(nil).WordWrap), text, width)
}

