// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/unix-streamdeck/api/v2 (interfaces: IConn)
//
// Generated by this command:
//
//      mockgen . IConn
//

// Package mock_api is a generated GoMock package.
package mock_api

import (
	reflect "reflect"

	dbus "github.com/godbus/dbus/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockIConn is a mock of IConn interface.
type MockIConn struct {
	ctrl     *gomock.Controller
	recorder *MockIConnMockRecorder
	isgomock struct{}
}

// MockIConnMockRecorder is the mock recorder for MockIConn.
type MockIConnMockRecorder struct {
	mock *MockIConn
}

// NewMockIConn creates a new mock instance.
func NewMockIConn(ctrl *gomock.Controller) *MockIConn {
	mock := &MockIConn{ctrl: ctrl}
	mock.recorder = &MockIConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConn) EXPECT() *MockIConnMockRecorder {
	return m.recorder
}

// AddMatchSignal mocks base method.
func (m *MockIConn) AddMatchSignal(options ...dbus.MatchOption) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddMatchSignal", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMatchSignal indicates an expected call of AddMatchSignal.
func (mr *MockIConnMockRecorder) AddMatchSignal(options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMatchSignal", reflect.TypeOf((*MockIConn)(nil).AddMatchSignal), options...)
}

// Close mocks base method.
func (m *MockIConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIConn)(nil).Close))
}

// Object mocks base method.
func (m *MockIConn) Object(dest string, path dbus.ObjectPath) dbus.BusObject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Object", dest, path)
	ret0, _ := ret[0].(dbus.BusObject)
	return ret0
}

// Object indicates an expected call of Object.
func (mr *MockIConnMockRecorder) Object(dest, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Object", reflect.TypeOf((*MockIConn)(nil).Object), dest, path)
}

// Signal mocks base method.
func (m *MockIConn) Signal(ch chan<- *dbus.Signal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Signal", ch)
}

// Signal indicates an expected call of Signal.
func (mr *MockIConnMockRecorder) Signal(ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockIConn)(nil).Signal), ch)
}
