// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/godbus/dbus/v5 (interfaces: BusObject)
//
// Generated by this command:
//
//      mockgen github.com/godbus/dbus/v5 BusObject
//

// Package mock_dbus is a generated GoMock package.
package mock_dbus

import (
	context "context"
	reflect "reflect"

	dbus "github.com/godbus/dbus/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockBusObject is a mock of BusObject interface.
type MockBusObject struct {
	ctrl     *gomock.Controller
	recorder *MockBusObjectMockRecorder
	isgomock struct{}
}

// MockBusObjectMockRecorder is the mock recorder for MockBusObject.
type MockBusObjectMockRecorder struct {
	mock *MockBusObject
}

// NewMockBusObject creates a new mock instance.
func NewMockBusObject(ctrl *gomock.Controller) *MockBusObject {
	mock := &MockBusObject{ctrl: ctrl}
	mock.recorder = &MockBusObjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusObject) EXPECT() *MockBusObjectMockRecorder {
	return m.recorder
}

// AddMatchSignal mocks base method.
func (m *MockBusObject) AddMatchSignal(iface, member string, options ...dbus.MatchOption) *dbus.Call {
	m.ctrl.T.Helper()
	varargs := []any{iface, member}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddMatchSignal", varargs...)
	ret0, _ := ret[0].(*dbus.Call)
	return ret0
}

// AddMatchSignal indicates an expected call of AddMatchSignal.
func (mr *MockBusObjectMockRecorder) AddMatchSignal(iface, member any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{iface, member}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMatchSignal", reflect.TypeOf((*MockBusObject)(nil).AddMatchSignal), varargs...)
}

// Call mocks base method.
func (m *MockBusObject) Call(method string, flags dbus.Flags, args ...any) *dbus.Call {
	m.ctrl.T.Helper()
	varargs := []any{method, flags}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Call", varargs...)
	ret0, _ := ret[0].(*dbus.Call)
	return ret0
}

// Call indicates an expected call of Call.
func (mr *MockBusObjectMockRecorder) Call(method, flags any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{method, flags}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockBusObject)(nil).Call), varargs...)
}

// CallWithContext mocks base method.
func (m *MockBusObject) CallWithContext(ctx context.Context, method string, flags dbus.Flags, args ...any) *dbus.Call {
	m.ctrl.T.Helper()
	varargs := []any{ctx, method, flags}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CallWithContext", varargs...)
	ret0, _ := ret[0].(*dbus.Call)
	return ret0
}

// CallWithContext indicates an expected call of CallWithContext.
func (mr *MockBusObjectMockRecorder) CallWithContext(ctx, method, flags any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, method, flags}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallWithContext", reflect.TypeOf((*MockBusObject)(nil).CallWithContext), varargs...)
}

// Destination mocks base method.
func (m *MockBusObject) Destination() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destination")
	ret0, _ := ret[0].(string)
	return ret0
}

// Destination indicates an expected call of Destination.
func (mr *MockBusObjectMockRecorder) Destination() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destination", reflect.TypeOf((*MockBusObject)(nil).Destination))
}

// GetProperty mocks base method.
func (m *MockBusObject) GetProperty(p string) (dbus.Variant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProperty", p)
	ret0, _ := ret[0].(dbus.Variant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProperty indicates an expected call of GetProperty.
func (mr *MockBusObjectMockRecorder) GetProperty(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProperty", reflect.TypeOf((*MockBusObject)(nil).GetProperty), p)
}

// Go mocks base method.
func (m *MockBusObject) Go(method string, flags dbus.Flags, ch chan *dbus.Call, args ...any) *dbus.Call {
	m.ctrl.T.Helper()
	varargs := []any{method, flags, ch}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Go", varargs...)
	ret0, _ := ret[0].(*dbus.Call)
	return ret0
}

// Go indicates an expected call of Go.
func (mr *MockBusObjectMockRecorder) Go(method, flags, ch any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{method, flags, ch}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Go", reflect.TypeOf((*MockBusObject)(nil).Go), varargs...)
}

// GoWithContext mocks base method.
func (m *MockBusObject) GoWithContext(ctx context.Context, method string, flags dbus.Flags, ch chan *dbus.Call, args ...any) *dbus.Call {
	m.ctrl.T.Helper()
	varargs := []any{ctx, method, flags, ch}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GoWithContext", varargs...)
	ret0, _ := ret[0].(*dbus.Call)
	return ret0
}

// GoWithContext indicates an expected call of GoWithContext.
func (mr *MockBusObjectMockRecorder) GoWithContext(ctx, method, flags, ch any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, method, flags, ch}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoWithContext", reflect.TypeOf((*MockBusObject)(nil).GoWithContext), varargs...)
}

// Path mocks base method.
func (m *MockBusObject) Path() dbus.ObjectPath {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(dbus.ObjectPath)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockBusObjectMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockBusObject)(nil).Path))
}

// RemoveMatchSignal mocks base method.
func (m *MockBusObject) RemoveMatchSignal(iface, member string, options ...dbus.MatchOption) *dbus.Call {
	m.ctrl.T.Helper()
	varargs := []any{iface, member}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveMatchSignal", varargs...)
	ret0, _ := ret[0].(*dbus.Call)
	return ret0
}

// RemoveMatchSignal indicates an expected call of RemoveMatchSignal.
func (mr *MockBusObjectMockRecorder) RemoveMatchSignal(iface, member any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{iface, member}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMatchSignal", reflect.TypeOf((*MockBusObject)(nil).RemoveMatchSignal), varargs...)
}

// SetProperty mocks base method.
func (m *MockBusObject) SetProperty(p string, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProperty", p, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProperty indicates an expected call of SetProperty.
func (mr *MockBusObjectMockRecorder) SetProperty(p, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProperty", reflect.TypeOf((*MockBusObject)(nil).SetProperty), p, v)
}

// StoreProperty mocks base method.
func (m *MockBusObject) StoreProperty(p string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreProperty", p, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreProperty indicates an expected call of StoreProperty.
func (mr *MockBusObjectMockRecorder) StoreProperty(p, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreProperty", reflect.TypeOf((*MockBusObject)(nil).StoreProperty), p, value)
}
